// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Abhyas",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Abhyas",
            targets: ["AppModule"],
            bundleIdentifier: "com.swifteers.Abhyas",
            teamIdentifier: "2H6VB94KW9",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .magicWand),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "We need camera access to capture your notes for text extraction."),
                .microphone(purposeString: "We need access to your microphone to record your explanation."),
                .speechRecognition(purposeString: "We will use speech recognition to transcribe your explanation.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)